---
title: Misanya Liu's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: A minimal blog Using Emerald.
url: http://misanya.com
author:
  name: Misanya Liu
  email: liushengxian1230@163.com
  url: http://misanya.com
baseurl: "/"
markdown: kramdown
source: "."
destination: "./_site"
permalink: "/blog/:title"
gems:
- jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
version: 1.2.0
tag_page: "/blog/tags"
category_page: "/blog/categories/"
custom_header: false
custom_nav_footer: false
reverse: false
